Bootstrap: docker
From: debian:jessie-slim

#Includes idba, trimmomatic, samtools, bwa, bedtools, freebayes, bbmap, vcftools, htslib, ncurses, kraken2, resistomeanalyzer, rarefactionanalyzer, SNPfinder

%environment
    echo 'export PATH=/usr/local/bin/anaconda/bin:${PATH}' >> $SINGULARITY_ENVIRONMENT
    export PATH=/usr/local/envs/compute/bin/:${PATH}

%files
    #environment.yml /
    
%post
    ## Jave install doesn't work, but can load java module from summit
    apt update \
    && apt install -y --no-install-recommends \
    build-essential ca-certificates sudo tcsh\
    git make automake autoconf openjdk-7-jre wget unzip sed \
    zlib1g-dev curl libbz2-dev locales libncurses5-dev liblzma-dev libcurl4-openssl-dev software-properties-common apt-transport-https\
    python3-pip python3-docopt python3-pytest python-dev python3-dev\
    libcurl4-openssl-dev libssl-dev zlib1g-dev fonts-texgyre \
    gcc g++ gfortran libblas-dev liblapack-dev dos2unix\
    r-base-core r-recommended hmmer\
    && rm -rf /var/lib/apt/lists/*

    #Installing Anaconda 2 and Conda 4.5.11
    wget -c https://repo.continuum.io/archive/Anaconda2-5.3.0-Linux-x86_64.sh
    sh Anaconda2-5.3.0-Linux-x86_64.sh -bfp /usr/local

    # add bioconda channels
    conda config --add channels defaults
    conda config --add channels conda-forge
    conda config --add channels bioconda
    
    # install bulk of bioinformatic tools using conda 
    conda create -n compute python=3 rgi idba trimmomatic bwa samtools bedtools freebayes bbmap vcftools htslib ncurses kraken2

    # make /data and /scripts so we can mount it to access external resources
    #if [ ! -d /data ]; then mkdir /data; fi
    #if [ ! -d /scripts ]; then mkdir /scripts; fi
    
    . /usr/local/bin/activate compute
        
    # resistomeanalyzer
    cd /usr/local
    git clone https://github.com/cdeanj/resistomeanalyzer.git
    cd resistomeanalyzer
    make
    cp resistome /usr/local/bin
    #ln -s /usr/local/resistomeanalyzer/* /usr/local/bin/
    cd /

    # RarefactionAnalyzer
    cd /usr/local
    git clone https://github.com/cdeanj/RarefactionAnalyzer.git
    cd RarefactionAnalyzer
    make
    cp rarefaction /usr/local/bin
    cd /
 
    # SNPfinder
    cd /usr/local
    git clone https://github.com/cdeanj/snpfinder.git
    cd snpfinder
    make
    cp snpfinder /usr/local/bin
    cd /    

    # Make sure all the tools have the right permissions to use the tools    
    chmod -R 777 /usr/local/

    
%test
    #which bwa
    #which bedtools
    #which samtools
    #which freebayes
