#!/bin/bash
# NEXTFLOW TASK: FAST_AMRplusplus:runqc (S1_test)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /home/enrique/Dropbox/Projects/AMR++_v3_update/AMRplusplus/work/f3/23278ab73e511059b4c0f42ff2eb87/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /home/enrique/Dropbox/Projects/AMR++_v3_update/AMRplusplus/work/f3/23278ab73e511059b4c0f42ff2eb87/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f S1_test_R1.fastq.gz
    rm -f S1_test_R2.fastq.gz
    ln -s /home/enrique/Dropbox/Projects/AMR++_v3_update/AMRplusplus/data/raw/S1_test_R1.fastq.gz S1_test_R1.fastq.gz
    ln -s /home/enrique/Dropbox/Projects/AMR++_v3_update/AMRplusplus/data/raw/S1_test_R2.fastq.gz S1_test_R2.fastq.gz
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/enrique/Dropbox/Projects/AMR++_v3_update/AMRplusplus/work/f3/23278ab73e511059b4c0f42ff2eb87/.command.begin
    set +u
    # conda environment
    source $(conda info --json | awk '/conda_prefix/ { gsub(/"|,/, "", $2); print $2 }')/bin/activate /home/enrique/anaconda3/envs/AmrPlusPlus_env
    set -u
    export threads="4"
    export JAVA="java"
    export TRIMMOMATIC="/home/enrique/anaconda3/envs/AmrPlusPlus_env/share/trimmomatic-0.39-2/trimmomatic.jar"
    export PYTHON3="python3"
    export BWA="bwa"
    export SAMTOOLS="samtools"
    export BEDTOOLS="bedtools"
    export RESISTOME="resistome"
    export RAREFACTION="rarefaction"
    export SNPFINDER="snpfinder"
    export FREEBAYES="freebayes"
    export KRAKEN2="kraken2"
    export RGI="rgi"
    export DIAMOND="diamond"
    export PATH="/home/enrique/Dropbox/Projects/AMR++_v3_update/AMRplusplus/bin:$PATH"
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    set +e
    ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
